sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t fqtools .
 - docker images | grep -c fqtools
 - docker run -v $HOME:/fqtools -it fqtools sh -c "cp -r /opt/wsi-t113/fqtools/* /fqtools/ && cd /fqtools/tests/test-commands && mkdir temp && ./command-test"
