#!/usr/bin/env bash
# Check two files by MD5 checksum and pretty print the result.
md5_1=`md5 -q $1`
md5_2=`md5 -q $2`
[[ ${md5_1} == ${md5_2} ]] && result="OK  " || result="FAIL"
echo "${result}: ${md5_1} & ${md5_2}"
